/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atmapp;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author x17500429
 */
public class AtmGui extends javax.swing.JFrame {
    protected Double balance;
    protected String accountNo;
    protected String pin;

    /**
     * Creates new form AtmGui
     */
    public AtmGui() {
        initComponents();
        
        loginGui log = new loginGui();
        Account a = new Account();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jOneBtn = new javax.swing.JButton();
        jTwoBtn = new javax.swing.JButton();
        jFourBtn = new javax.swing.JButton();
        jFiveBtn = new javax.swing.JButton();
        jSevenBtn = new javax.swing.JButton();
        jEightBtn = new javax.swing.JButton();
        jNineBtn = new javax.swing.JButton();
        jSixBtn = new javax.swing.JButton();
        jThreeBtn = new javax.swing.JButton();
        jZeroBtn = new javax.swing.JButton();
        jBlanck2Btn = new javax.swing.JButton();
        jBlank1Btn = new javax.swing.JButton();
        jCancelBtn = new javax.swing.JButton();
        jClearBtn = new javax.swing.JButton();
        jEnterBtn = new javax.swing.JButton();
        jBlank3Btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtnBalance = new javax.swing.JButton();
        jbtnWithdraw = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtnNext = new javax.swing.JButton();
        jbtnDeposit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jlblDisplay = new javax.swing.JLabel();
        jlblBalance = new javax.swing.JLabel();
        jlblNext = new javax.swing.JLabel();
        jlblDeposit = new javax.swing.JLabel();
        jlblWithdraw = new javax.swing.JLabel();
        jFrame = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jReset = new javax.swing.JButton();
        jReceipt = new javax.swing.JButton();
        jExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jReceiptTA = new javax.swing.JTextArea();
        TitlePanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jOneBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/One1.JPG"))); // NOI18N
        jOneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOneBtnActionPerformed(evt);
            }
        });

        jTwoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Two2.JPG"))); // NOI18N
        jTwoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTwoBtnActionPerformed(evt);
            }
        });

        jFourBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Four4.JPG"))); // NOI18N
        jFourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFourBtnActionPerformed(evt);
            }
        });

        jFiveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Five5.JPG"))); // NOI18N
        jFiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFiveBtnActionPerformed(evt);
            }
        });

        jSevenBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Seven7.JPG"))); // NOI18N
        jSevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjSevenBtnActionPerformed(evt);
            }
        });

        jEightBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Eight8.JPG"))); // NOI18N
        jEightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjEightBtnActionPerformed(evt);
            }
        });

        jNineBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/nine9.JPG"))); // NOI18N
        jNineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjNineBtnActionPerformed(evt);
            }
        });

        jSixBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Six6.JPG"))); // NOI18N
        jSixBtn.setName(""); // NOI18N
        jSixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjSixBtnActionPerformed(evt);
            }
        });

        jThreeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Three3.JPG"))); // NOI18N
        jThreeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThreeBtnActionPerformed(evt);
            }
        });

        jZeroBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Zero0.JPG"))); // NOI18N
        jZeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZeroBtnActionPerformed(evt);
            }
        });

        jBlanck2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Blank10.JPG"))); // NOI18N
        jBlanck2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlanck2BtnActionPerformed(evt);
            }
        });

        jBlank1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Blank10.JPG"))); // NOI18N
        jBlank1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlank1BtnActionPerformed(evt);
            }
        });

        jCancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Cancel.JPG"))); // NOI18N
        jCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelBtnActionPerformed(evt);
            }
        });

        jClearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Clear.JPG"))); // NOI18N
        jClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjClearBtnActionPerformed(evt);
            }
        });

        jEnterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Enter.JPG"))); // NOI18N
        jEnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjEnterBtnActionPerformed(evt);
            }
        });

        jBlank3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Blank.JPG"))); // NOI18N
        jBlank3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlank3BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jOneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTwoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jThreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jFourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBlank1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jZeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBlanck2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBlank3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jEightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jNineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jEnterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTwoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jThreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEnterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jZeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBlanck2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBlank1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBlank3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setPreferredSize(new java.awt.Dimension(160, 200));

        jbtnBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Right.JPG"))); // NOI18N
        jbtnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBalanceActionPerformed(evt);
            }
        });

        jbtnWithdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Right.JPG"))); // NOI18N
        jbtnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnWithdrawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jbtnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setPreferredSize(new java.awt.Dimension(160, 200));

        jbtnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Left.JPG"))); // NOI18N
        jbtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNextActionPerformed(evt);
            }
        });

        jbtnDeposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/Left.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDeposit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jlblDisplay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jlblBalance.setText("Balance");

        jlblNext.setText("Next");

        jlblDeposit.setText("Deposit");

        jlblWithdraw.setText("Withdraw");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jlblDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblBalance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblNext))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblWithdraw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblDeposit)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblBalance)
                    .addComponent(jlblNext))
                .addGap(18, 18, 18)
                .addComponent(jlblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDeposit)
                    .addComponent(jlblWithdraw))
                .addGap(39, 39, 39))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.setPreferredSize(new java.awt.Dimension(854, 630));

        jReset.setText("Reset");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });

        jReceipt.setText("Receipt");
        jReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReceiptActionPerformed(evt);
            }
        });

        jExit.setText("Exit");
        jExit.setToolTipText("");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        jReceiptTA.setColumns(20);
        jReceiptTA.setRows(5);
        jScrollPane2.setViewportView(jReceiptTA);

        TitlePanel.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        TitlePanel.setText("ATM System");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jReset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameLayout = new javax.swing.GroupLayout(jFrame);
        jFrame.setLayout(jFrameLayout);
        jFrameLayout.setHorizontalGroup(
            jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jFrameLayout.setVerticalGroup(
            jFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOneBtnActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "1";
        jlblDisplay.setText(Enternumber);
        
    }//GEN-LAST:event_jOneBtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jReset.setEnabled(false);
        jExit.setEnabled(false);
        jReceipt.setEnabled(false);
        jbtnBalance.setEnabled(false);
        jbtnNext.setEnabled(false);
        jbtnWithdraw.setEnabled(false);
        jbtnDeposit.setEnabled(false);
        
        jPanel4.setVisible(true);
        jlblBalance.setVisible(false);
        jlblNext.setVisible(false);
        jlblWithdraw.setVisible(false);
        jlblDeposit.setVisible(false);
        
    }//GEN-LAST:event_formWindowActivated

    private void jTwoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTwoBtnActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "2";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jTwoBtnActionPerformed

    private void jThreeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThreeBtnActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "3";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jThreeBtnActionPerformed

    private void jFourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFourBtnActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "4";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jFourBtnActionPerformed

    private void jFiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFiveBtnActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "5";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jFiveBtnActionPerformed

    private void jjSixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjSixBtnActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "6";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jjSixBtnActionPerformed

    private void jjSevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjSevenBtnActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "7";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jjSevenBtnActionPerformed

    private void jjEightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjEightBtnActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "8";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jjEightBtnActionPerformed

    private void jjNineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjNineBtnActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "9";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jjNineBtnActionPerformed

    private void jZeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZeroBtnActionPerformed
        // TODO add your handling code here:
        String Enternumber = jlblDisplay.getText() + "0";
        jlblDisplay.setText(Enternumber);
    }//GEN-LAST:event_jZeroBtnActionPerformed

    private void jjClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjClearBtnActionPerformed
        // TODO add your handling code here:
        jlblDisplay.setText("");
        
        jReset.setEnabled(false);
        jExit.setEnabled(false);
        jReceipt.setEnabled(false);
        jbtnBalance.setEnabled(false);
        jbtnNext.setEnabled(false);
        jbtnWithdraw.setEnabled(false);
        jbtnDeposit.setEnabled(false);
    }//GEN-LAST:event_jjClearBtnActionPerformed

    private void jjEnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjEnterBtnActionPerformed
        // TODO add your handling code here:
       int userInput1 = Integer.parseInt(jlblDisplay.getText());

        if(userInput1 == 4782){
        jbtnBalance.setEnabled(true);
        jbtnNext.setEnabled(true);
        jbtnWithdraw.setEnabled(true);
        jbtnDeposit.setEnabled(true);
        jlblBalance.setVisible(true);
        jlblNext.setVisible(true);
        jlblWithdraw.setVisible(true);
        jlblDeposit.setVisible(true);
                
        }else if(userInput1== 3209){ 
        jbtnBalance.setEnabled(true);
        jbtnNext.setEnabled(true);
        jbtnWithdraw.setEnabled(true);
        jbtnDeposit.setEnabled(true);
        jlblBalance.setVisible(true);
        jlblNext.setVisible(true);
        jlblWithdraw.setVisible(true);
        jlblDeposit.setVisible(true);
        
        }else if(userInput1==5639){
        jbtnBalance.setEnabled(true);
        jbtnNext.setEnabled(true);
        jbtnWithdraw.setEnabled(true);
        jbtnDeposit.setEnabled(true);
        jlblBalance.setVisible(true);
        jlblNext.setVisible(true);
        jlblWithdraw.setVisible(true);
        jlblDeposit.setVisible(true);
        }
                else
        {
            jlblDisplay.setText("Invalid, try again!");
        }
    }//GEN-LAST:event_jjEnterBtnActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
        //jFrame = new frame("Exit");
        if (JOptionPane.showConfirmDialog(jFrame, "Confirm if you want to exit",
            "ATMif (JOptionPane.showConfirmDialog(jFrame, \"Confirm if you want to exit\",\n"
                + "            \"Loan Management Systems\",\n"
                + "            JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){\n"
                + "            this.setDefaultCloseOperation(AtmGui.EXIT_ON_CLOSE);\n"
                + "            this.dispose(); Systems",
            JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            this.setDefaultCloseOperation(AtmGui.EXIT_ON_CLOSE);
            this.dispose();
        //System.exit(0);

        }
    }//GEN-LAST:event_jExitActionPerformed

    private void jReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReceiptActionPerformed
        // TODO add your handling code here:
        
        //calender time
            Calendar timer = Calendar.getInstance();
                timer.getTime();
                SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
                tTime.format(timer.getTime());
                SimpleDateFormat tDate = new SimpleDateFormat("dd-MMM-yyyy");
                tDate.format(timer.getTime());
                
        
        //What will be shown in jReceiptTA
        jReceiptTA.append("\t         Thank You For \n "
                + "\t        Using Our Bank\n "
                + "\t        Your Receipt is:\n\n\n"
                + "Balance:\t\t\t 100000"
                + "\n ===============================================\t "
                + "\n\n\n\nDate: " + tDate.format(timer.getTime())
                + "\nTime: " + tTime.format(timer.getTime())
                + "\n\n\n\n\t          Thank you again");

    }//GEN-LAST:event_jReceiptActionPerformed

    private void jbtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNextActionPerformed
        // TODO add your handling code here:
        jReset.setEnabled(true);
        jExit.setEnabled(true);
        jReceipt.setEnabled(true);
    }//GEN-LAST:event_jbtnNextActionPerformed

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
        // TODO add your handling code here:
        jReset.setEnabled(true);
        jExit.setEnabled(true);
        jReceipt.setEnabled(true);
        
        jReceiptTA.setText(null);
    }//GEN-LAST:event_jResetActionPerformed

    private void jBlanck2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlanck2BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBlanck2BtnActionPerformed

    private void jBlank1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlank1BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBlank1BtnActionPerformed

    private void jBlank3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlank3BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBlank3BtnActionPerformed

    private void jCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelBtnActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(jFrame, "Confirm if you want to exit",
            "ATM Systems",
            JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            this.setDefaultCloseOperation(AtmGui.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_jCancelBtnActionPerformed

    private void jbtnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBalanceActionPerformed

    private void jbtnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnWithdrawActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbtnWithdrawActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtmGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtmGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtmGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtmGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtmGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitlePanel;
    private javax.swing.JButton jBlanck2Btn;
    private javax.swing.JButton jBlank1Btn;
    private javax.swing.JButton jBlank3Btn;
    private javax.swing.JButton jCancelBtn;
    private javax.swing.JButton jClearBtn;
    private javax.swing.JButton jEightBtn;
    private javax.swing.JButton jEnterBtn;
    private javax.swing.JButton jExit;
    private javax.swing.JButton jFiveBtn;
    private javax.swing.JButton jFourBtn;
    private javax.swing.JPanel jFrame;
    private javax.swing.JButton jNineBtn;
    private javax.swing.JButton jOneBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jReceipt;
    private javax.swing.JTextArea jReceiptTA;
    private javax.swing.JButton jReset;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSevenBtn;
    private javax.swing.JButton jSixBtn;
    private javax.swing.JButton jThreeBtn;
    private javax.swing.JButton jTwoBtn;
    private javax.swing.JButton jZeroBtn;
    private javax.swing.JButton jbtnBalance;
    private javax.swing.JButton jbtnDeposit;
    private javax.swing.JButton jbtnNext;
    private javax.swing.JButton jbtnWithdraw;
    private javax.swing.JLabel jlblBalance;
    private javax.swing.JLabel jlblDeposit;
    private javax.swing.JLabel jlblDisplay;
    private javax.swing.JLabel jlblNext;
    private javax.swing.JLabel jlblWithdraw;
    // End of variables declaration//GEN-END:variables
}
