/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atmapp;
import javax.swing.JOptionPane;

/**
 *
 * @author x17500429
 */
public class loginGui extends javax.swing.JFrame {
    
    protected String accountNo;
    protected String pin;
    protected boolean validAccountNo = false;
    protected boolean validPin = false;
    protected boolean validLogin = false;

    /**
     * Creates new form loginGui
     */
    public loginGui() {
        initComponents();
    }
    
    public loginGui(String accountNo, String pin) {
        this.accountNo = accountNo;
        this.pin = pin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitle = new javax.swing.JLabel();
        jlblAccountNo = new javax.swing.JLabel();
        jlblPin = new javax.swing.JLabel();
        jAccountNoTF = new javax.swing.JTextField();
        jPinTF = new javax.swing.JTextField();
        jbtnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTitle.setText("Welcome to our Bank");

        jlblAccountNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblAccountNo.setText("Account Number:");

        jlblPin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblPin.setText("Pin:");

        jbtnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmapp/LogIn.JPG"))); // NOI18N
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jlblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblAccountNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPinTF, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jAccountNoTF)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblPin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jlblTitle)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAccountNo)
                    .addComponent(jAccountNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPin)
                    .addComponent(jPinTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        // TODO add your handling code here:
        accountNo = jAccountNoTF.getText();
        pin = jPinTF.getText();
        
        LogIn atm = new LogIn(accountNo, pin);
        atm.setAccountNo(accountNo);
        atm.setPin(pin);
        validAccountNo = atm.CheckAccountNo();
        validPin = atm.CheckPin();
        
        Account acc = new Account();
        acc.setAccountNo(accountNo);
        acc.setPin(pin);
        acc.generateBalance();
        
        jAccountNoTF.setText("");
        jPinTF.setText("");
        //testing lines
        System.out.println("account "  + accountNo);
        System.out.println("pin "  + pin);
        
        //validAccountNo = atm.isValidAccountNo();
        
        //validPin = atm.isValidPin();
        //testing lines
        System.out.println("validAccountNo"  +validAccountNo);
        System.out.println("validPin"  +validPin);
       
        if (validAccountNo && validPin) {
            JOptionPane.showMessageDialog(null, "Welcome, Thank you for using our bank, Your account number is " + accountNo);
            
            AtmGui gui = new AtmGui();
            gui.setVisible(true);
            
            this.setVisible(false);
            this.setDefaultCloseOperation(loginGui.EXIT_ON_CLOSE);
            
            LogIn log = new LogIn();
            log.validateLogin(validAccountNo, validPin);
            validLogin = log.isValidLogin();
            
        } else if(!validAccountNo || !validPin) {
            JOptionPane.showMessageDialog(null, "Not a real Account number,"
                    + "\nMust be 10 digits.\n"); 
        
        
    }//GEN-LAST:event_jbtnLoginActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAccountNoTF;
    private javax.swing.JTextField jPinTF;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JLabel jlblAccountNo;
    private javax.swing.JLabel jlblPin;
    private javax.swing.JLabel jlblTitle;
    // End of variables declaration//GEN-END:variables
}
